### ISSUE TITLE
Cannot find module 'vis'.

### ISSUE THREAD

**Issue by joel00** [seveves/ng2-vis#3]
After installing 0.0.1-3

Cannot find module 'vis'.
`import * as Vis from 'vis';`

error in types:

`  public visNetworkData: Vis.IData;`
`  public visNetworkOptions: Vis.IOptions;`

**Comment by seveves** [comment]
Thanks for testing! I will check the typings configuration.

**Comment by seveves** [comment]
Would you mind testing ng2-vis@0.0.1-6 and tell me if this fixes the problem for you?

**Comment by joel00** [comment]
Hi there.... yes now it's working with **ng2-vis@0.0.1-6**

Thanks, I'll follow close this project!

**Comment by seveves** [comment]
That's great! I'll close the issue then. By the way which visjs module (network, graph2d, timeline ...) are you going to use the most?

**Comment by joel00** [comment]
The module I use the most by far is network!

**Comment by AndrewLang** [comment]
I still have this issue in version 0.0.4, should I configure the systemjs.config.js?
